// <auto-generated />
using System;
using MindBot.Infrastructure.State;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MindBot.Infrastructure.State.Migrations;

[DbContext(typeof(MindBotDbContext))]
[Migration("20260731140000_AddWriteJobRelativeFolder")]
partial class AddWriteJobRelativeFolder
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

        modelBuilder.Entity("MindBot.Infrastructure.State.ConversationStateEntity", b =>
            {
                b.Property<long>("ChatId")
                    .HasColumnType("INTEGER");

                b.Property<string>("PendingNoteName")
                    .HasColumnType("TEXT");

                b.Property<int>("Stage")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("ChatId");

                b.ToTable("Conversations", (string)null);
            });

        modelBuilder.Entity("MindBot.Infrastructure.State.ProcessedUpdateEntity", b =>
            {
                b.Property<long>("UpdateId")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset>("ReceivedAt")
                    .HasColumnType("TEXT");

                b.HasKey("UpdateId");

                b.HasIndex("ReceivedAt");

                b.ToTable("ProcessedUpdates", (string)null);
            });

        modelBuilder.Entity("MindBot.Infrastructure.State.RepositoryStateEntity", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset?>("LastSuccessfulPushAt")
                    .HasColumnType("TEXT");

                b.Property<string>("LastPushedSha")
                    .HasColumnType("TEXT");

                b.Property<int>("LastTelegramOffset")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("RepositoryState", (string)null);
            });

        modelBuilder.Entity("MindBot.Infrastructure.State.WriteJobEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<long>("ChatId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("EnqueuedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Filename")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("RelativeFolder")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("SenderId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<long>("UpdateId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("RelativeFolder", "Filename", "Status");

                b.HasIndex("Status", "Id");

                b.ToTable("WriteJobs", (string)null);
            });
    }
}
