<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MindBot.Bot-cdde26f0-0d0b-4417-ab2e-9374d963c855</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Telegram.Bot" Version="22.10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MindBot.Core\MindBot.Core.csproj" />
    <ProjectReference Include="..\MindBot.Infrastructure\MindBot.Infrastructure.csproj" />
  </ItemGroup>
</Project>
